// Generated by scripts/generate-icons.mjs. Do not edit — run `npm run brand:build`.
export const FAVICON_DATA_URI =
  'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22960%22 height=%22960%22 viewBox=%220 0 960 960%22%3E %3Cpath transform=%22translate(0,960)%22 d=%22M677-409 409-677l268-267 267 267-267 268ZM31-489v-379h378v379H31ZM489-31v-378h379v378H489ZM31-31v-378h378v378H31Z%22 fill=%22%236366f1%22/%3E %3C/svg%3E';
