import type { ToolDefinition, ToolMode } from '@/types/tools';

export const toolRegistry: Record<ToolMode, ToolDefinition> = {
  // ─── IMAGE ──────────────────────────────────────────────────────────────────
  'png-to-jpg': {
    id: 'png-to-jpg',
    category: 'image',
    icon: 'image',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-blue-500/20 border-indigo-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/png'],
    related: ['jpg-to-png', 'webp-to-jpg', 'compress-image'],
    keywords: ['png to jpg', 'convert png to jpg', 'png to jpeg', 'png converter'],
  },
  'jpg-to-png': {
    id: 'jpg-to-png',
    category: 'image',
    icon: 'image',
    colorClass: 'text-blue-400',
    iconBgClass: 'from-blue-500/20 to-cyan-500/20 border-blue-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg'],
    related: ['png-to-jpg', 'compress-image', 'resize-image'],
    keywords: ['jpg to png', 'convert jpg to png', 'jpeg to png', 'jpg converter'],
  },
  'video-to-gif': {
    id: 'video-to-gif',
    category: 'image',
    icon: 'animation',
    colorClass: 'text-fuchsia-400',
    iconBgClass: 'from-fuchsia-500/20 to-purple-500/20 border-fuchsia-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['video/mp4', 'video/webm', 'video/quicktime'],
    related: ['mp4-to-gif', 'compress-image', 'image-batch'],
    keywords: ['video to gif', 'convert video to gif', 'mp4 to gif', 'webm to gif', 'free gif converter'],
  },
  'mp4-to-gif': {
    id: 'mp4-to-gif',
    category: 'image',
    icon: 'animation',
    colorClass: 'text-fuchsia-400',
    iconBgClass: 'from-fuchsia-500/20 to-purple-500/20 border-fuchsia-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['video/mp4'],
    related: ['video-to-gif', 'compress-image', 'image-batch'],
    keywords: ['mp4 to gif', 'convert mp4 to gif', 'mp4 gif converter', 'video to gif online free'],
  },
  'webp-to-jpg': {
    id: 'webp-to-jpg',
    category: 'image',
    icon: 'image',
    colorClass: 'text-violet-400',
    iconBgClass: 'from-violet-500/20 to-purple-500/20 border-violet-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/webp'],
    related: ['jpg-to-webp', 'webp-to-png', 'compress-image'],
    keywords: ['webp to jpg', 'convert webp to jpg', 'webp to jpeg', 'webp converter'],
  },
  'jpg-to-webp': {
    id: 'jpg-to-webp',
    category: 'image',
    icon: 'image',
    colorClass: 'text-fuchsia-400',
    iconBgClass: 'from-fuchsia-500/20 to-pink-500/20 border-fuchsia-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png'],
    related: ['webp-to-jpg', 'png-to-webp', 'compress-image'],
    keywords: ['jpg to webp', 'convert jpg to webp', 'jpeg to webp', 'webp converter'],
  },
  'webp-to-png': {
    id: 'webp-to-png',
    category: 'image',
    icon: 'swap_horiz',
    colorClass: 'text-purple-400',
    iconBgClass: 'from-purple-500/20 to-violet-500/20 border-purple-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/webp'],
    related: ['webp-to-jpg', 'png-to-webp', 'compress-image'],
    keywords: ['webp to png', 'convert webp to png', 'webp png converter'],
  },
  'png-to-webp': {
    id: 'png-to-webp',
    category: 'image',
    icon: 'swap_horiz',
    colorClass: 'text-teal-400',
    iconBgClass: 'from-teal-500/20 to-cyan-500/20 border-teal-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/png'],
    related: ['jpg-to-webp', 'webp-to-png', 'compress-image'],
    keywords: ['png to webp', 'convert png to webp', 'png webp converter'],
  },
  'heic-to-jpg': {
    id: 'heic-to-jpg',
    category: 'image',
    icon: 'photo_camera',
    colorClass: 'text-rose-400',
    iconBgClass: 'from-rose-500/20 to-pink-500/20 border-rose-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/heic', 'image/heif', '.heic', '.heif'],
    related: ['heic-to-png', 'png-to-jpg', 'compress-image'],
    keywords: ['heic to jpg', 'convert heic to jpg', 'heic converter', 'iphone photo converter'],
  },
  'heic-to-png': {
    id: 'heic-to-png',
    category: 'image',
    icon: 'photo_camera',
    colorClass: 'text-pink-400',
    iconBgClass: 'from-pink-500/20 to-rose-500/20 border-pink-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/heic', 'image/heif', '.heic', '.heif'],
    related: ['heic-to-jpg', 'jpg-to-png', 'compress-image'],
    keywords: ['heic to png', 'convert heic to png', 'heic converter', 'iphone photo to png'],
  },
  'avif-to-jpg': {
    id: 'avif-to-jpg',
    category: 'image',
    icon: 'image',
    colorClass: 'text-lime-400',
    iconBgClass: 'from-lime-500/20 to-green-500/20 border-lime-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/avif'],
    related: ['avif-to-png', 'webp-to-jpg', 'compress-image'],
    keywords: ['avif to jpg', 'convert avif to jpg', 'avif converter'],
  },
  'avif-to-png': {
    id: 'avif-to-png',
    category: 'image',
    icon: 'image',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/avif'],
    related: ['avif-to-jpg', 'webp-to-png', 'compress-image'],
    keywords: ['avif to png', 'convert avif to png', 'avif converter'],
  },
  'svg-to-png': {
    id: 'svg-to-png',
    category: 'image',
    icon: 'shapes',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-amber-500/20 border-yellow-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/svg+xml', '.svg'],
    related: ['svg-to-jpg', 'png-to-jpg', 'compress-image'],
    keywords: ['svg to png', 'convert svg to png', 'svg converter', 'vector to raster'],
  },
  'svg-to-jpg': {
    id: 'svg-to-jpg',
    category: 'image',
    icon: 'shapes',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-yellow-500/20 border-amber-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/svg+xml', '.svg'],
    related: ['svg-to-png', 'compress-image', 'resize-image'],
    keywords: ['svg to jpg', 'convert svg to jpg', 'svg converter', 'vector to jpeg'],
  },
  'compress-image': {
    id: 'compress-image',
    category: 'image',
    icon: 'compress',
    colorClass: 'text-emerald-400',
    iconBgClass: 'from-emerald-500/20 to-teal-500/20 border-emerald-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['resize-image', 'png-to-jpg', 'jpg-to-webp'],
    keywords: ['compress image', 'reduce image size', 'image compressor', 'optimize image'],
  },
  'remove-bg': {
    id: 'remove-bg',
    category: 'image',
    icon: 'auto_fix_high',
    colorClass: 'text-violet-400',
    iconBgClass: 'from-violet-500/20 to-purple-500/20 border-violet-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['add-watermark', 'image-filter', 'compress-image'],
    keywords: ['remove background', 'background remover', 'transparent background', 'remove bg'],
  },
  'resize-image': {
    id: 'resize-image',
    category: 'image',
    icon: 'photo_size_select_large',
    colorClass: 'text-cyan-400',
    iconBgClass: 'from-cyan-500/20 to-teal-500/20 border-cyan-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['crop-image', 'compress-image', 'image-batch'],
    keywords: ['resize image', 'image resizer', 'change image size', 'scale image'],
  },
  'crop-image': {
    id: 'crop-image',
    category: 'image',
    icon: 'crop',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-orange-500/20 border-amber-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['resize-image', 'rotate-image', 'compress-image'],
    keywords: ['crop image', 'image cropper', 'trim image', 'cut image'],
  },
  'rotate-image': {
    id: 'rotate-image',
    category: 'image',
    icon: 'rotate_right',
    colorClass: 'text-orange-400',
    iconBgClass: 'from-orange-500/20 to-red-500/20 border-orange-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['crop-image', 'resize-image', 'image-filter'],
    keywords: ['rotate image', 'image rotator', 'turn image', 'flip image 90 degrees'],
  },
  'image-filter': {
    id: 'image-filter',
    category: 'image',
    icon: 'filter_vintage',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['compress-image', 'add-watermark', 'resize-image'],
    keywords: ['image filter', 'photo filter', 'image effects', 'photo editor online'],
  },

  // ─── PDF ────────────────────────────────────────────────────────────────────
  'image-to-pdf': {
    id: 'image-to-pdf',
    category: 'pdf',
    icon: 'image',
    colorClass: 'text-violet-400',
    iconBgClass: 'from-violet-500/20 to-indigo-500/20 border-violet-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['merge-pdf', 'compress-image', 'pdf-compress'],
    keywords: ['image to pdf', 'images to pdf', 'jpg to pdf', 'png to pdf', 'convert images to pdf', 'photos to pdf'],
  },
  'merge-pdf': {
    id: 'merge-pdf',
    category: 'pdf',
    icon: 'picture_as_pdf',
    colorClass: 'text-red-400',
    iconBgClass: 'from-red-500/20 to-rose-500/20 border-red-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['application/pdf'],
    related: ['split-pdf', 'pdf-compress', 'pdf-watermark'],
    keywords: ['merge pdf', 'combine pdf', 'join pdf files', 'pdf merger'],
  },
  'split-pdf': {
    id: 'split-pdf',
    category: 'pdf',
    icon: 'call_split',
    colorClass: 'text-rose-400',
    iconBgClass: 'from-rose-500/20 to-pink-500/20 border-rose-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['application/pdf'],
    related: ['merge-pdf', 'pdf-to-txt', 'pdf-compress'],
    keywords: ['split pdf', 'divide pdf', 'extract pdf pages', 'pdf splitter'],
  },
  'pdf-compress': {
    id: 'pdf-compress',
    category: 'pdf',
    icon: 'compress',
    colorClass: 'text-orange-400',
    iconBgClass: 'from-orange-500/20 to-red-500/20 border-orange-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['application/pdf'],
    related: ['merge-pdf', 'split-pdf', 'compress-image'],
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor', 'shrink pdf'],
  },
  'pdf-encrypt': {
    id: 'pdf-encrypt',
    category: 'pdf',
    icon: 'lock',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-yellow-500/20 border-amber-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['application/pdf'],
    related: ['pdf-decrypt', 'merge-pdf', 'pdf-watermark'],
    keywords: ['encrypt pdf', 'password protect pdf', 'secure pdf', 'pdf password'],
  },
  'pdf-decrypt': {
    id: 'pdf-decrypt',
    category: 'pdf',
    icon: 'lock_open',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-lime-500/20 border-yellow-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['application/pdf'],
    related: ['pdf-encrypt', 'merge-pdf', 'split-pdf'],
    keywords: ['decrypt pdf', 'remove pdf password', 'unlock pdf', 'pdf decryption'],
  },
  'pdf-watermark': {
    id: 'pdf-watermark',
    category: 'pdf',
    icon: 'branding_watermark',
    colorClass: 'text-lime-400',
    iconBgClass: 'from-lime-500/20 to-green-500/20 border-lime-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['application/pdf'],
    related: ['add-watermark', 'pdf-encrypt', 'merge-pdf'],
    keywords: ['pdf watermark', 'add watermark to pdf', 'stamp pdf'],
  },
  'pdf-to-txt': {
    id: 'pdf-to-txt',
    category: 'pdf',
    icon: 'text_snippet',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 20,
    acceptedFormats: ['application/pdf'],
    related: ['split-pdf', 'merge-pdf', 'word-counter'],
    keywords: ['pdf to text', 'extract text from pdf', 'pdf text extractor'],
  },
  'pdf-to-csv': {
    id: 'pdf-to-csv',
    category: 'pdf',
    icon: 'table_chart',
    colorClass: 'text-teal-400',
    iconBgClass: 'from-teal-500/20 to-cyan-500/20 border-teal-500/20',
    maxFileSizeMB: 20,
    acceptedFormats: ['application/pdf'],
    related: ['pdf-to-txt', 'csv-formatter', 'split-pdf'],
    keywords: ['pdf to csv', 'extract table from pdf', 'pdf csv converter'],
  },
  'pdf-to-word': {
    id: 'pdf-to-word',
    category: 'pdf',
    icon: 'description',
    colorClass: 'text-blue-400',
    iconBgClass: 'from-blue-500/20 to-indigo-500/20 border-blue-500/20',
    maxFileSizeMB: 20,
    acceptedFormats: ['application/pdf'],
    related: ['pdf-to-txt', 'word-to-pdf', 'merge-pdf'],
    keywords: ['pdf to word', 'convert pdf to word', 'pdf to docx', 'pdf to doc'],
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    category: 'pdf',
    icon: 'picture_as_pdf',
    colorClass: 'text-red-400',
    iconBgClass: 'from-red-500/20 to-rose-500/20 border-red-500/20',
    maxFileSizeMB: 20,
    acceptedFormats: ['.docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    related: ['pdf-to-word', 'merge-pdf', 'pdf-compress'],
    keywords: ['word to pdf', 'convert word to pdf', 'docx to pdf', 'doc to pdf'],
  },

  // ─── DEV ────────────────────────────────────────────────────────────────────
  'json-formatter': {
    id: 'json-formatter',
    category: 'dev',
    icon: 'data_object',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-amber-500/20 border-yellow-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: [],
    related: ['json-validator', 'base64', 'yaml-formatter'],
    keywords: ['json formatter', 'json beautifier', 'format json', 'json validator', 'json minifier'],
  },
  'base64': {
    id: 'base64',
    category: 'dev',
    icon: 'code',
    colorClass: 'text-lime-400',
    iconBgClass: 'from-lime-500/20 to-green-500/20 border-lime-500/20',
    maxFileSizeMB: 1,
    acceptedFormats: [],
    related: ['text-encoder', 'hash-generator', 'uuid-generator'],
    keywords: ['base64 encoder', 'base64 decoder', 'base64 encode decode', 'encode base64'],
  },
  'uuid-generator': {
    id: 'uuid-generator',
    category: 'dev',
    icon: 'fingerprint',
    colorClass: 'text-purple-400',
    iconBgClass: 'from-purple-500/20 to-violet-500/20 border-purple-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['password-generator', 'hash-generator', 'timestamp-converter'],
    keywords: ['uuid generator', 'generate uuid', 'unique id generator', 'guid generator'],
  },
  'timestamp-converter': {
    id: 'timestamp-converter',
    category: 'dev',
    icon: 'schedule',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['time-diff', 'uuid-generator', 'json-formatter'],
    keywords: ['timestamp converter', 'unix timestamp', 'epoch converter', 'date converter'],
  },
  'json-validator': {
    id: 'json-validator',
    category: 'dev',
    icon: 'check_circle',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: [],
    related: ['json-formatter', 'yaml-formatter', 'xml-formatter'],
    keywords: ['json validator', 'validate json', 'json lint', 'check json'],
  },
  'regex-tester': {
    id: 'regex-tester',
    category: 'dev',
    icon: 'manage_search',
    colorClass: 'text-orange-400',
    iconBgClass: 'from-orange-500/20 to-amber-500/20 border-orange-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['json-formatter', 'text-case', 'word-counter'],
    keywords: ['regex tester', 'regular expression tester', 'regex validator', 'regex online'],
  },
  'text-case': {
    id: 'text-case',
    category: 'dev',
    icon: 'text_format',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-blue-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['word-counter', 'lorem-ipsum', 'markdown-formatter'],
    keywords: ['text case converter', 'camelCase', 'snake_case', 'uppercase lowercase'],
  },
  'lorem-ipsum': {
    id: 'lorem-ipsum',
    category: 'dev',
    icon: 'article',
    colorClass: 'text-violet-400',
    iconBgClass: 'from-violet-500/20 to-purple-500/20 border-violet-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['word-counter', 'text-case', 'markdown-formatter'],
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text generator'],
  },
  'hash-generator': {
    id: 'hash-generator',
    category: 'dev',
    icon: 'tag',
    colorClass: 'text-red-400',
    iconBgClass: 'from-red-500/20 to-rose-500/20 border-red-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['base64', 'uuid-generator', 'password-generator'],
    keywords: ['hash generator', 'md5 hash', 'sha256 hash', 'checksum generator'],
  },
  'qr-reader': {
    id: 'qr-reader',
    category: 'dev',
    icon: 'qr_code_scanner',
    colorClass: 'text-cyan-400',
    iconBgClass: 'from-cyan-500/20 to-teal-500/20 border-cyan-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp'],
    related: ['qr-code', 'base64', 'text-encoder'],
    keywords: ['qr code reader', 'qr code scanner', 'decode qr code', 'read qr code'],
  },
  'csv-formatter': {
    id: 'csv-formatter',
    category: 'dev',
    icon: 'table_chart',
    colorClass: 'text-teal-400',
    iconBgClass: 'from-teal-500/20 to-cyan-500/20 border-teal-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: [],
    related: ['json-formatter', 'xml-formatter', 'yaml-formatter'],
    keywords: ['csv formatter', 'csv validator', 'csv parser', 'format csv'],
  },
  'xml-formatter': {
    id: 'xml-formatter',
    category: 'dev',
    icon: 'code',
    colorClass: 'text-blue-400',
    iconBgClass: 'from-blue-500/20 to-indigo-500/20 border-blue-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: [],
    related: ['json-formatter', 'yaml-formatter', 'csv-formatter'],
    keywords: ['xml formatter', 'xml beautifier', 'format xml', 'xml validator'],
  },
  'yaml-formatter': {
    id: 'yaml-formatter',
    category: 'dev',
    icon: 'code',
    colorClass: 'text-emerald-400',
    iconBgClass: 'from-emerald-500/20 to-teal-500/20 border-emerald-500/20',
    maxFileSizeMB: 5,
    acceptedFormats: [],
    related: ['json-formatter', 'xml-formatter', 'csv-formatter'],
    keywords: ['yaml formatter', 'yaml validator', 'format yaml', 'yaml parser'],
  },
  'markdown-formatter': {
    id: 'markdown-formatter',
    category: 'dev',
    icon: 'article',
    colorClass: 'text-fuchsia-400',
    iconBgClass: 'from-fuchsia-500/20 to-pink-500/20 border-fuchsia-500/20',
    maxFileSizeMB: 2,
    acceptedFormats: [],
    related: ['word-counter', 'text-case', 'lorem-ipsum'],
    keywords: ['markdown editor', 'markdown preview', 'markdown formatter', 'md to html'],
  },

  // ─── LIGHT ──────────────────────────────────────────────────────────────────
  'word-counter': {
    id: 'word-counter',
    category: 'light',
    icon: 'text_fields',
    colorClass: 'text-teal-400',
    iconBgClass: 'from-teal-500/20 to-cyan-500/20 border-teal-500/20',
    maxFileSizeMB: 1,
    acceptedFormats: [],
    related: ['text-case', 'lorem-ipsum', 'markdown-formatter'],
    keywords: ['word counter', 'character counter', 'word count', 'count words online'],
  },
  'qr-code': {
    id: 'qr-code',
    category: 'light',
    icon: 'qr_code',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-blue-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['qr-reader', 'password-generator', 'uuid-generator'],
    keywords: ['qr code generator', 'generate qr code', 'free qr code', 'qr code maker'],
  },
  'password-generator': {
    id: 'password-generator',
    category: 'light',
    icon: 'lock',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['uuid-generator', 'hash-generator', 'qr-code'],
    keywords: ['password generator', 'random password', 'secure password', 'strong password generator'],
  },
  'timezone-converter': {
    id: 'timezone-converter',
    category: 'light',
    icon: 'schedule',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['time-diff', 'date-calculator', 'timestamp-converter'],
    keywords: ['timezone converter', 'time zone', 'world clock', 'time difference', 'DST'],
  },
  'ip-lookup': {
    id: 'ip-lookup',
    category: 'light',
    icon: 'travel_explore',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['ip-calculator', 'password-generator', 'timezone-converter'],
    keywords: ['ip lookup', 'ip address lookup', 'ip geolocation', 'my ip address', 'ip location'],
  },
  'ocr-tool': {
    id: 'ocr-tool',
    category: 'light',
    icon: 'document_scanner',
    colorClass: 'text-violet-400',
    iconBgClass: 'from-violet-500/20 to-purple-500/20 border-violet-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['qr-reader', 'pdf-to-txt', 'word-counter'],
    keywords: ['ocr', 'optical character recognition', 'extract text from image', 'image to text', 'tesseract'],
  },
  'us-address-generator': {
    id: 'us-address-generator',
    category: 'light',
    icon: 'location_on',
    colorClass: 'text-rose-400',
    iconBgClass: 'from-rose-500/20 to-pink-500/20 border-rose-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['password-generator', 'ip-lookup', 'timezone-converter'],
    keywords: ['us address generator', 'random address', 'fake address', 'random us address', 'address generator', 'random name generator'],
  },

  // ─── CALC ───────────────────────────────────────────────────────────────────
  'base-convert': {
    id: 'base-convert',
    category: 'calc',
    icon: 'calculate',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['binary-calculator', 'bitwise-calculator', 'text-encoder'],
    keywords: ['base converter', 'number base', 'decimal to binary', 'hex to decimal', 'binary converter'],
  },
  'random-number': {
    id: 'random-number',
    category: 'calc',
    icon: 'casino',
    colorClass: 'text-pink-400',
    iconBgClass: 'from-pink-500/20 to-rose-500/20 border-pink-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['password-generator', 'uuid-generator', 'bmi-calculator'],
    keywords: ['random number generator', 'random number', 'dice roller', 'random integer'],
  },
  'binary-calculator': {
    id: 'binary-calculator',
    category: 'calc',
    icon: 'computer',
    colorClass: 'text-lime-400',
    iconBgClass: 'from-lime-500/20 to-green-500/20 border-lime-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['base-convert', 'bitwise-calculator', 'boolean-calculator'],
    keywords: ['binary calculator', 'binary arithmetic', 'binary addition', 'binary math'],
  },
  'boolean-calculator': {
    id: 'boolean-calculator',
    category: 'calc',
    icon: 'rule',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-orange-500/20 border-amber-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['binary-calculator', 'bitwise-calculator', 'base-convert'],
    keywords: ['boolean calculator', 'boolean logic', 'logic gates', 'boolean expression'],
  },
  'bitwise-calculator': {
    id: 'bitwise-calculator',
    category: 'calc',
    icon: 'memory',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['binary-calculator', 'boolean-calculator', 'base-convert'],
    keywords: ['bitwise calculator', 'bitwise AND OR XOR', 'bit shift', 'bitwise operations'],
  },
  'ip-calculator': {
    id: 'ip-calculator',
    category: 'calc',
    icon: 'lan',
    colorClass: 'text-teal-400',
    iconBgClass: 'from-teal-500/20 to-cyan-500/20 border-teal-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['base-convert', 'binary-calculator', 'bitwise-calculator'],
    keywords: ['ip calculator', 'subnet calculator', 'cidr calculator', 'ip subnet mask'],
  },
  'time-diff': {
    id: 'time-diff',
    category: 'calc',
    icon: 'timelapse',
    colorClass: 'text-violet-400',
    iconBgClass: 'from-violet-500/20 to-purple-500/20 border-violet-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['timestamp-converter', 'loan-calculator', 'bmi-calculator'],
    keywords: ['time difference calculator', 'date difference', 'days between dates', 'age calculator'],
  },
  'bmi-calculator': {
    id: 'bmi-calculator',
    category: 'calc',
    icon: 'monitor_weight',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['loan-calculator', 'time-diff', 'random-number'],
    keywords: ['bmi calculator', 'body mass index', 'healthy weight calculator', 'bmi formula'],
  },
  'loan-calculator': {
    id: 'loan-calculator',
    category: 'calc',
    icon: 'account_balance',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-amber-500/20 border-yellow-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['bmi-calculator', 'time-diff', 'random-number'],
    keywords: ['loan calculator', 'mortgage calculator', 'monthly payment calculator', 'amortization'],
  },
  'matrix-calculator': {
    id: 'matrix-calculator',
    category: 'calc',
    icon: 'grid_on',
    colorClass: 'text-cyan-400',
    iconBgClass: 'from-cyan-500/20 to-teal-500/20 border-cyan-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['binary-calculator', 'bitwise-calculator', 'base-convert'],
    keywords: ['matrix calculator', 'matrix multiplication', 'matrix addition', 'transpose matrix'],
  },
  'string-analyzer': {
    id: 'string-analyzer',
    category: 'calc',
    icon: 'manage_search',
    colorClass: 'text-rose-400',
    iconBgClass: 'from-rose-500/20 to-pink-500/20 border-rose-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['word-counter', 'text-case', 'hash-generator'],
    keywords: ['string analyzer', 'text statistics', 'character count', 'word frequency', 'string length'],
  },
  'date-calculator': {
    id: 'date-calculator',
    category: 'calc',
    icon: 'event',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['time-diff', 'bmi-calculator', 'loan-calculator'],
    keywords: ['date calculator', 'add days to date', 'subtract days from date', 'date arithmetic', 'days from now'],
  },

  // ─── FINANCE ────────────────────────────────────────────────────────────────
  'bank-bin': {
    id: 'bank-bin',
    category: 'finance',
    icon: 'credit_card',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-amber-500/20 border-yellow-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['currency-converter', 'password-generator', 'uuid-generator'],
    keywords: ['bank bin lookup', 'card bin checker', 'credit card issuer', 'bin iin lookup', 'card number info'],
  },
  'currency-converter': {
    id: 'currency-converter',
    category: 'finance',
    icon: 'currency_exchange',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-amber-500/20 border-yellow-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['bank-bin', 'loan-calculator', 'bmi-calculator'],
    keywords: ['currency converter', 'exchange rate', 'forex', 'usd to eur', 'currency exchange', 'real time exchange rate'],
  },
  'unit-converter': {
    id: 'unit-converter',
    category: 'calc',
    icon: 'straighten',
    colorClass: 'text-orange-400',
    iconBgClass: 'from-orange-500/20 to-amber-500/20 border-orange-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['base-convert', 'bmi-calculator', 'time-diff'],
    keywords: ['unit converter', 'length converter', 'weight converter', 'temperature converter', 'metric imperial'],
  },

  // ─── ENCODE ─────────────────────────────────────────────────────────────────
  'text-encoder': {
    id: 'text-encoder',
    category: 'encode',
    icon: 'translate',
    colorClass: 'text-fuchsia-400',
    iconBgClass: 'from-fuchsia-500/20 to-pink-500/20 border-fuchsia-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['base64', 'hash-generator', 'qr-code'],
    keywords: [
      'text encoder decoder', 'encoding converter', 'hex encoder', 'binary encoder',
      'base64 converter', 'url encoder decoder', 'morse code translator',
    ],
  },
  'online-notepad': {
    id: 'online-notepad',
    category: 'encode',
    icon: 'edit_note',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-yellow-500/20 border-amber-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['text-encoder', 'word-counter', 'markdown-formatter'],
    keywords: ['online notepad', 'text editor online', 'notepad', 'markdown editor', 'note taking'],
  },

  // ─── AUDIO ──────────────────────────────────────────────────────────────────
  'audio-trim': {
    id: 'audio-trim',
    category: 'audio',
    icon: 'content_cut',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/x-m4a', 'audio/webm'],
    related: ['audio-split', 'audio-merge', 'audio-volume'],
    keywords: ['audio trimmer', 'trim audio', 'cut audio', 'mp3 trimmer online'],
  },
  'audio-split': {
    id: 'audio-split',
    category: 'audio',
    icon: 'call_split',
    colorClass: 'text-rose-400',
    iconBgClass: 'from-rose-500/20 to-pink-500/20 border-rose-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/x-m4a', 'audio/webm'],
    related: ['audio-trim', 'audio-merge', 'split-pdf'],
    keywords: ['audio splitter', 'split audio', 'divide audio file', 'split mp3'],
  },
  'audio-volume': {
    id: 'audio-volume',
    category: 'audio',
    icon: 'volume_up',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/x-m4a', 'audio/webm'],
    related: ['audio-trim', 'audio-denoise', 'audio-convert'],
    keywords: ['audio volume booster', 'increase audio volume', 'mp3 volume changer'],
  },
  'audio-convert': {
    id: 'audio-convert',
    category: 'audio',
    icon: 'swap_horiz',
    colorClass: 'text-sky-400',
    iconBgClass: 'from-sky-500/20 to-blue-500/20 border-sky-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/x-m4a', 'audio/webm'],
    related: ['audio-trim', 'audio-volume', 'compress-image'],
    keywords: ['audio converter', 'mp3 to wav', 'convert audio format', 'audio file converter'],
  },
  'audio-merge': {
    id: 'audio-merge',
    category: 'audio',
    icon: 'merge',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-orange-500/20 border-amber-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/x-m4a', 'audio/webm'],
    related: ['audio-split', 'audio-trim', 'merge-pdf'],
    keywords: ['audio merger', 'merge audio files', 'combine mp3', 'join audio'],
  },
  'audio-denoise': {
    id: 'audio-denoise',
    category: 'audio',
    icon: 'graphic_eq',
    colorClass: 'text-teal-400',
    iconBgClass: 'from-teal-500/20 to-cyan-500/20 border-teal-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4', 'audio/x-m4a', 'audio/webm'],
    related: ['audio-volume', 'audio-trim', 'audio-convert'],
    keywords: ['audio denoiser', 'remove noise from audio', 'audio cleaner', 'noise reduction'],
  },
  'add-watermark': {
    id: 'add-watermark',
    category: 'image',
    icon: 'branding_watermark',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-blue-500/20 border-indigo-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['image-filter', 'remove-bg', 'pdf-watermark'],
    keywords: ['add watermark', 'watermark image', 'photo watermark', 'image copyright'],
  },
  'drawing-canvas': {
    id: 'drawing-canvas',
    category: 'image',
    icon: 'draw',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-orange-500/20 border-amber-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['add-watermark', 'image-filter', 'svg-to-png'],
    keywords: ['online drawing canvas', 'draw online', 'digital whiteboard', 'paint online free'],
  },
  'image-batch': {
    id: 'image-batch',
    category: 'image',
    icon: 'view_module',
    colorClass: 'text-cyan-400',
    iconBgClass: 'from-cyan-500/20 to-teal-500/20 border-cyan-500/20',
    maxFileSizeMB: 50,
    acceptedFormats: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    related: ['resize-image', 'compress-image', 'add-watermark'],
    keywords: ['batch resize images', 'bulk image resizer', 'resize multiple images', 'batch image editor'],
  },

  // ─── GAME ───────────────────────────────────────────────────────────────────
  'aim-trainer': {
    id: 'aim-trainer',
    category: 'game',
    icon: 'ads_click',
    colorClass: 'text-rose-400',
    iconBgClass: 'from-rose-500/20 to-pink-500/20 border-rose-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cps-test', 'reaction-test'],
    keywords: ['aim trainer', 'aim practice', 'mouse accuracy test', 'fps aim training', 'click accuracy'],
  },
  'cps-test': {
    id: 'cps-test',
    category: 'game',
    icon: 'mouse',
    colorClass: 'text-green-400',
    iconBgClass: 'from-green-500/20 to-emerald-500/20 border-green-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['reaction-test', 'sensitivity-converter', 'aim-trainer'],
    keywords: ['cps test', 'clicks per second', 'click speed test', 'mouse click speed'],
  },
  'reaction-test': {
    id: 'reaction-test',
    category: 'game',
    icon: 'bolt',
    colorClass: 'text-yellow-400',
    iconBgClass: 'from-yellow-500/20 to-amber-500/20 border-yellow-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cps-test', 'sensitivity-converter'],
    keywords: ['reaction time test', 'reflex test', 'reaction speed', 'gaming reaction test'],
  },
  'sensitivity-converter': {
    id: 'sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-blue-400',
    iconBgClass: 'from-blue-500/20 to-indigo-500/20 border-blue-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cps-test', 'reaction-test', 'cs2-to-valorant-sensitivity'],
    keywords: ['sensitivity converter', 'mouse sensitivity calculator', 'game sensitivity', 'fps sensitivity'],
  },
  'valorant-sensitivity-converter': {
    id: 'valorant-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-red-400',
    iconBgClass: 'from-red-500/20 to-pink-500/20 border-red-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-valorant-sensitivity', 'apex-to-valorant-sensitivity', 'sensitivity-converter'],
    keywords: ['valorant sensitivity converter', 'valorant sens calculator', 'valorant mouse sensitivity'],
  },
  'cs2-sensitivity-converter': {
    id: 'cs2-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-orange-400',
    iconBgClass: 'from-orange-500/20 to-amber-500/20 border-orange-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-valorant-sensitivity', 'cs2-to-apex-sensitivity', 'sensitivity-converter'],
    keywords: ['cs2 sensitivity converter', 'csgo sensitivity calculator', 'counter strike sensitivity'],
  },
  'apex-sensitivity-converter': {
    id: 'apex-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-orange-300',
    iconBgClass: 'from-orange-400/20 to-red-500/20 border-orange-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['apex-to-valorant-sensitivity', 'apex-to-cs2-sensitivity', 'sensitivity-converter'],
    keywords: ['apex legends sensitivity converter', 'apex sens calculator', 'apex mouse sensitivity'],
  },
  'overwatch2-sensitivity-converter': {
    id: 'overwatch2-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-orange-400',
    iconBgClass: 'from-orange-500/20 to-yellow-500/20 border-orange-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['overwatch2-to-valorant-sensitivity', 'overwatch2-to-cs2-sensitivity', 'sensitivity-converter'],
    keywords: ['overwatch 2 sensitivity converter', 'overwatch sens calculator', 'ow2 mouse sensitivity'],
  },
  'r6siege-sensitivity-converter': {
    id: 'r6siege-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-cyan-400',
    iconBgClass: 'from-cyan-500/20 to-blue-500/20 border-cyan-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['rainbow six siege sensitivity converter', 'r6 sens calculator', 'siege mouse sensitivity'],
  },
  'pubg-sensitivity-converter': {
    id: 'pubg-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-amber-400',
    iconBgClass: 'from-amber-500/20 to-yellow-500/20 border-amber-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['pubg-to-cs2-sensitivity', 'sensitivity-converter'],
    keywords: ['pubg sensitivity converter', 'pubg sens calculator', 'pubg mouse sensitivity'],
  },
  'fortnite-sensitivity-converter': {
    id: 'fortnite-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-blue-300',
    iconBgClass: 'from-blue-400/20 to-purple-500/20 border-blue-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['fortnite-to-valorant-sensitivity', 'sensitivity-converter'],
    keywords: ['fortnite sensitivity converter', 'fortnite sens calculator', 'fortnite mouse sensitivity'],
  },
  'cod-sensitivity-converter': {
    id: 'cod-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-green-300',
    iconBgClass: 'from-green-400/20 to-emerald-500/20 border-green-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cod-to-cs2-sensitivity', 'sensitivity-converter'],
    keywords: ['call of duty sensitivity converter', 'cod warzone sens calculator', 'cod mouse sensitivity'],
  },
  'tarkov-sensitivity-converter': {
    id: 'tarkov-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-slate-300',
    iconBgClass: 'from-slate-400/20 to-gray-500/20 border-slate-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['escape from tarkov sensitivity converter', 'tarkov sens calculator', 'eft mouse sensitivity'],
  },
  'bf2042-sensitivity-converter': {
    id: 'bf2042-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-yellow-300',
    iconBgClass: 'from-yellow-400/20 to-orange-500/20 border-yellow-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['battlefield 2042 sensitivity converter', 'bf2042 sens calculator', 'battlefield mouse sensitivity'],
  },
  'halo-sensitivity-converter': {
    id: 'halo-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-teal-300',
    iconBgClass: 'from-teal-400/20 to-cyan-500/20 border-teal-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['halo infinite sensitivity converter', 'halo sens calculator', 'halo mouse sensitivity'],
  },
  'thefinals-sensitivity-converter': {
    id: 'thefinals-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-purple-300',
    iconBgClass: 'from-purple-400/20 to-pink-500/20 border-purple-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['the finals sensitivity converter', 'the finals sens calculator', 'the finals mouse sensitivity'],
  },
  'warframe-sensitivity-converter': {
    id: 'warframe-sensitivity-converter',
    category: 'game',
    icon: 'settings_input_component',
    colorClass: 'text-sky-300',
    iconBgClass: 'from-sky-400/20 to-blue-500/20 border-sky-400/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['warframe sensitivity converter', 'warframe sens calculator', 'warframe mouse sensitivity'],
  },
  'cs2-to-valorant-sensitivity': {
    id: 'cs2-to-valorant-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['valorant-to-cs2-sensitivity', 'cs2-sensitivity-converter', 'valorant-sensitivity-converter'],
    keywords: ['cs2 to valorant sensitivity', 'csgo to valorant sens converter', 'cs2 valorant sensitivity calculator'],
  },
  'valorant-to-cs2-sensitivity': {
    id: 'valorant-to-cs2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-valorant-sensitivity', 'valorant-sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['valorant to cs2 sensitivity', 'valorant to csgo sens converter', 'valorant cs2 sensitivity calculator'],
  },
  'apex-to-valorant-sensitivity': {
    id: 'apex-to-valorant-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['valorant-to-apex-sensitivity', 'apex-sensitivity-converter', 'valorant-sensitivity-converter'],
    keywords: ['apex to valorant sensitivity', 'apex legends valorant sens converter', 'apex valorant sensitivity'],
  },
  'valorant-to-apex-sensitivity': {
    id: 'valorant-to-apex-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['apex-to-valorant-sensitivity', 'valorant-sensitivity-converter', 'apex-sensitivity-converter'],
    keywords: ['valorant to apex sensitivity', 'valorant apex legends sens converter', 'valorant apex sensitivity'],
  },
  'cs2-to-apex-sensitivity': {
    id: 'cs2-to-apex-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['apex-to-cs2-sensitivity', 'cs2-sensitivity-converter', 'apex-sensitivity-converter'],
    keywords: ['cs2 to apex sensitivity', 'csgo apex legends sens converter', 'cs2 apex sensitivity calculator'],
  },
  'apex-to-cs2-sensitivity': {
    id: 'apex-to-cs2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-apex-sensitivity', 'apex-sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['apex to cs2 sensitivity', 'apex legends csgo sens converter', 'apex cs2 sensitivity calculator'],
  },
  'overwatch2-to-valorant-sensitivity': {
    id: 'overwatch2-to-valorant-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['valorant-to-overwatch2-sensitivity', 'overwatch2-sensitivity-converter'],
    keywords: ['overwatch 2 to valorant sensitivity', 'ow2 valorant sens converter', 'overwatch valorant sensitivity'],
  },
  'valorant-to-overwatch2-sensitivity': {
    id: 'valorant-to-overwatch2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['overwatch2-to-valorant-sensitivity', 'valorant-sensitivity-converter'],
    keywords: ['valorant to overwatch 2 sensitivity', 'valorant ow2 sens converter', 'valorant overwatch sensitivity'],
  },
  'cs2-to-overwatch2-sensitivity': {
    id: 'cs2-to-overwatch2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['overwatch2-to-cs2-sensitivity', 'cs2-sensitivity-converter', 'overwatch2-sensitivity-converter'],
    keywords: ['cs2 to overwatch 2 sensitivity', 'csgo ow2 sens converter', 'cs2 overwatch sensitivity'],
  },
  'overwatch2-to-cs2-sensitivity': {
    id: 'overwatch2-to-cs2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-overwatch2-sensitivity', 'overwatch2-sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['overwatch 2 to cs2 sensitivity', 'ow2 csgo sens converter', 'overwatch cs2 sensitivity'],
  },
  'pubg-to-cs2-sensitivity': {
    id: 'pubg-to-cs2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-pubg-sensitivity', 'pubg-sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['pubg to cs2 sensitivity', 'pubg csgo sens converter', 'pubg cs2 sensitivity calculator'],
  },
  'cs2-to-pubg-sensitivity': {
    id: 'cs2-to-pubg-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['pubg-to-cs2-sensitivity', 'cs2-sensitivity-converter', 'pubg-sensitivity-converter'],
    keywords: ['cs2 to pubg sensitivity', 'csgo pubg sens converter', 'cs2 pubg sensitivity calculator'],
  },
  'fortnite-to-valorant-sensitivity': {
    id: 'fortnite-to-valorant-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['valorant-to-fortnite-sensitivity', 'fortnite-sensitivity-converter', 'valorant-sensitivity-converter'],
    keywords: ['fortnite to valorant sensitivity', 'fortnite valorant sens converter', 'fortnite valorant sensitivity'],
  },
  'valorant-to-fortnite-sensitivity': {
    id: 'valorant-to-fortnite-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['fortnite-to-valorant-sensitivity', 'valorant-sensitivity-converter', 'fortnite-sensitivity-converter'],
    keywords: ['valorant to fortnite sensitivity', 'valorant fortnite sens converter', 'valorant fortnite sensitivity'],
  },
  'cod-to-cs2-sensitivity': {
    id: 'cod-to-cs2-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cs2-to-cod-sensitivity', 'cod-sensitivity-converter', 'cs2-sensitivity-converter'],
    keywords: ['call of duty to cs2 sensitivity', 'cod warzone csgo sens converter', 'cod cs2 sensitivity'],
  },
  'cs2-to-cod-sensitivity': {
    id: 'cs2-to-cod-sensitivity',
    category: 'game',
    icon: 'compare_arrows',
    colorClass: 'text-indigo-400',
    iconBgClass: 'from-indigo-500/20 to-violet-500/20 border-indigo-500/20',
    maxFileSizeMB: 0,
    acceptedFormats: [],
    related: ['cod-to-cs2-sensitivity', 'cs2-sensitivity-converter', 'cod-sensitivity-converter'],
    keywords: ['cs2 to call of duty sensitivity', 'csgo cod warzone sens converter', 'cs2 cod sensitivity'],
  },
};

export const toolsByCategory = {
  image: Object.values(toolRegistry).filter(t => t.category === 'image'),
  pdf: Object.values(toolRegistry).filter(t => t.category === 'pdf'),
  dev: Object.values(toolRegistry).filter(t => t.category === 'dev'),
  light: Object.values(toolRegistry).filter(t => t.category === 'light'),
  calc: Object.values(toolRegistry).filter(t => t.category === 'calc'),
  finance: Object.values(toolRegistry).filter(t => t.category === 'finance'),
  encode: Object.values(toolRegistry).filter(t => t.category === 'encode'),
  audio: Object.values(toolRegistry).filter(t => t.category === 'audio'),
  edit: Object.values(toolRegistry).filter(t => t.category === 'edit'),
  game: Object.values(toolRegistry).filter(t => t.category === 'game'),
};

export const popularTools: ToolMode[] = [
  'png-to-jpg',
  'video-to-gif',
  'bank-bin',
  'currency-converter',
  'text-encoder',
  'json-formatter',
  'base64',
  'qr-code',
  'password-generator',
  'remove-bg',
  'sensitivity-converter',
  'hash-generator',
];
