/**
 * Renders every brand icon from scripts/brand.mjs.
 *
 * Transparent glyph, for the browser tab:
 *   public/favicon.svg          vector
 *
 * Opaque tile, for anywhere the icon is drawn onto someone else's surface — and for the
 * .ico, per the note beside it:
 *   public/favicon.ico          16 + 32 + 48, for engines that don't take the SVG
 *   public/apple-touch-icon.png 180x180  iOS home screen
 *   public/icon-192.png         192x192  web manifest
 *   public/icon-512.png         512x512  web manifest
 *   public/og-icon.png          1200x1200 og:image
 *
 * See scripts/brand.mjs for why the split exists.
 *
 * Output is committed, so deploys never need a rasterizer. Regenerate on a machine
 * with @resvg/resvg-js available:
 *     npm i --no-save @resvg/resvg-js && npm run brand:build
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { glyphSvg, tileSvg } from './brand.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');

const { Resvg } = await import('@resvg/resvg-js').catch(() => {
  throw new Error(
    'Rendering the brand icons needs @resvg/resvg-js:\n' +
      '  npm i --no-save @resvg/resvg-js && npm run brand:build\n' +
      'The output is committed, so this is only needed when the mark changes.'
  );
});

const tile = tileSvg();
const glyph = glyphSvg();

const render = (svg, size) =>
  Buffer.from(new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng());

const png = (size) => render(tile, size);
const glyphPng = (size) => render(glyph, size);

/**
 * Packs PNGs into an ICO container. ICO has carried PNG payloads since Vista and every
 * browser that still asks for favicon.ico reads them, so there's no need to emit BMP.
 */
function ico(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(images.length, 4);

  let offset = 6 + images.length * 16;
  const entries = images.map(({ size, data }) => {
    const e = Buffer.alloc(16);
    e.writeUInt8(size >= 256 ? 0 : size, 0); // width  (0 means 256)
    e.writeUInt8(size >= 256 ? 0 : size, 1); // height
    e.writeUInt8(0, 2); // palette size — 0 for truecolor
    e.writeUInt8(0, 3); // reserved
    e.writeUInt16LE(1, 4); // colour planes
    e.writeUInt16LE(32, 6); // bits per pixel
    e.writeUInt32LE(data.length, 8);
    e.writeUInt32LE(offset, 12);
    offset += data.length;
    return e;
  });

  return Buffer.concat([header, ...entries, ...images.map((i) => i.data)]);
}

const outputs = [
  ['favicon.svg', Buffer.from(glyph + '\n', 'utf8')],
  /*
   * Not declared in <head> — see src/app/layout.tsx. This is the file a browser fetches
   * from the origin root on its own when it can't use the declared SVG, which is engines
   * without SVG favicon support, and the surfaces that have always read /favicon.ico
   * directly rather than parsing the page: bookmarks, start-page favourites, history.
   *
   * Opaque, unlike favicon.svg, because those surfaces won't draw an .ico with
   * transparency in it — iOS substitutes a globe. feb92a0 shipped an opaque one and iOS
   * drew it; b66c810 shipped a transparent one in a byte-identical container and iOS drew
   * a globe, which isolates transparency from the container.
   */
  ['favicon.ico', ico([16, 32, 48].map((size) => ({ size, data: png(size) })))],
  ['apple-touch-icon.png', png(180)],
  ['icon-192.png', png(192)],
  ['icon-512.png', png(512)],
  // og:image. Square on purpose — see the note in src/lib/utils/seo.ts.
  ['og-icon.png', png(1200)],
];

for (const [name, data] of outputs) {
  writeFileSync(join(PUBLIC, name), data);
  console.log(`✓ ${name.padEnd(21)} ${(data.length / 1024).toFixed(1)} KB`);
}

/*
 * The same glyph again, as a data URI, for the <link rel="icon"> in the root layout.
 *
 * A favicon is normally a separate request, and the browser gives it the lowest priority
 * it has. When that request is slow or times out, Safari draws a globe and doesn't retry —
 * which is why a fresh load of the same page showed the mark some visits and not others,
 * and why nothing done to the file's contents ever moved it. Inlined there is no request
 * to lose, and one fewer round trip on first paint.
 *
 * Generated rather than pasted so it can't drift from public/favicon.svg. The quotes are
 * encoded along with <, >, # and %, which leaves a value containing no character that
 * either a JS string literal or an HTML attribute has to escape — the alternative was
 * every quote arriving in the markup as &#x27;.
 */
const dataUri =
  'data:image/svg+xml,' +
  glyph.replace(/\n\s*/g, ' ').replace(/["<>#%]/g, (c) => encodeURIComponent(c));

writeFileSync(
  join(ROOT, 'src', 'lib', 'brand', 'favicon.ts'),
  '// Generated by scripts/generate-icons.mjs. Do not edit — run `npm run brand:build`.\n' +
    `export const FAVICON_DATA_URI =\n  '${dataUri}';\n`
);
console.log(`✓ ${'src/lib/brand/favicon.ts'.padEnd(21)} ${dataUri.length} chars inline`);
